### ISSUE TITLE
Remove references to the podcast since it's now just a newsletter

### ISSUE THREAD

**Issue by jonfriskics** [codeschool/JavaScript.com#321]
- [ ] https://github.com/codeschool/JavaScript.com/blob/master/server/views/index.jade#L44-L46
- [ ]  https://github.com/codeschool/JavaScript.com/blob/master/server/views/news/index.jade#L69-L77
- [ ] https://github.com/codeschool/JavaScript.com/blob/master/server/views/_globals/links.jade#L8-L10

**Comment by johndjameson** [comment]
Added in 3a6432f1a571b65fb36f4182ab0586010e205ce6
